const NEW_CHAT = "NEW_CHAT"
const NEW_MESSAGE = "NEW_MESSAGE"
const CHAT_ERROR = "CHAT_ERROR"
const NEW_NOTIFICATION = "NEW_NOTIFICATION"

export { NEW_CHAT, NEW_MESSAGE, CHAT_ERROR, NEW_NOTIFICATION }
